@startuml

title __APP's Class Diagram__\n

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.CameraAct {
    }
  }
  

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.Classifier {
    }
  }
  

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.CvCameraPreview {
    }
  }
  

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.MainActivity {
    }
  }
  

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.MyAndroidFrameConverter {
    }
  }
  

  namespace com.danhyal.NEA {
    abstract class com.danhyal.NEA.MyOpenCVFrameConverter {
    }
  }
  

  namespace com.danhyal.NEA {
    class com.danhyal.NEA.NetworkChoice {
    }
  }
  

  namespace com.example.testapplications {
    class com.example.testapplications.BuildConfig {
    }
  }
  

  com.danhyal.NEA.CameraAct .up.|> com.danhyal.NEA.CvCameraPreview.CvCameraViewListener
  com.danhyal.NEA.CameraAct -up-|> androidx.appcompat.app.AppCompatActivity
  com.danhyal.NEA.CameraAct o-- com.danhyal.NEA.CvCameraPreview : javacvviewbase
  com.danhyal.NEA.CvCameraPreview .up.|> android.hardware.Camera.PreviewCallback
  com.danhyal.NEA.CvCameraPreview .up.|> android.view.SurfaceHolder.Callback
  com.danhyal.NEA.CvCameraPreview -up-|> android.view.SurfaceView
  com.danhyal.NEA.CvCameraPreview o-- com.danhyal.NEA.MyOpenCVFrameConverter.ToUMat : converterToUmat
  com.danhyal.NEA.CvCameraPreview o-- com.danhyal.NEA.CvCameraPreview.CvCameraViewListener : listener
  com.danhyal.NEA.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.danhyal.NEA.MyAndroidFrameConverter -up-|> org.bytedeco.javacv.FrameConverter
  com.danhyal.NEA.MyOpenCVFrameConverter -up-|> org.bytedeco.javacv.FrameConverter
  com.danhyal.NEA.NetworkChoice .up.|> com.danhyal.NEA.CvCameraPreview.CvCameraViewListener
  com.danhyal.NEA.NetworkChoice -up-|> androidx.appcompat.app.AppCompatActivity
  com.danhyal.NEA.NetworkChoice o-- com.danhyal.NEA.CvCameraPreview : base


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
